Migrating from wpa_supplicant to iwd

diff --git a/.local/bin/wifi-connect-core b/.local/bin/wifi-connect-core
--- a/.local/bin/wifi-connect-core
+++ b/.local/bin/wifi-connect-core
@@ -2,38 +2,74 @@
 
 [ $# -eq 0 ] && exit 1
 
-list_network() {
-  wpa_cli list_network | tail -n +3 | \
-    {
-      tab='	'
-      newline='
-'
-      list=
-      while IFS=$tab read -r number ssid bssid flags; do
-        case $flags in
-          *\[CURRENT\]*)
-            printf "%s\t[CURRENT]\n" "$ssid"
-            break
-            ;;
-          *)
-            list=$list$ssid$newline
-            ;;
-        esac
-      done
+if [ -z "$interface" ]; then
+  configfile=${XDG_CONFIG_HOME:-$HOME/.config}/wifi-connect
 
-      printf "%s" "$list"
+  if ! [ -f "$configfile" ]; then
+    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}"
+    wifi-connect-generate-config >"$configfile"
 
-      while IFS=$tab read -r number ssid bssid flags; do
-        printf "%s\n" "$ssid"
-      done
-    }
+    if ! [ -f "$configfile" ]; then
+      echo "Unable to create config file" >&2
+      exit 1
+    fi
+  fi
+
+  . "$configfile"
+fi
+
+ifindex=$(cat "/sys/class/net/$interface/ifindex")
+phyx=$(cat "/sys/class/net/$interface/phy80211/index")
+
+print_if_is_network() {
+  local name
+  name=$(busctl --json short --system get-property \
+    net.connman.iwd "$1" \
+    net.connman.iwd.Network Name 2>/dev/null | fj -r '.data' 2>/dev/null)
+
+  if [ "$?" -eq 0 ]; then
+    printf "%s" "$name"
+    return 0
+  else
+    return 1
+  fi
 }
+
+list_network() {
+  busctl --system tree net.connman.iwd \
+    | sed -n 's@^.* \(/net/connman/iwd/'"$phyx/$ifindex"'/.*\)$@\1@p' \
+    | \
+    while IFS= read -r object; do
+      if ! name=$(print_if_is_network "$object"); then
+        continue
+      fi
+
+      if [ -n "$1" ]; then
+        if [ "$name" = "$1" ]; then
+          printf "%s" "$object"
+          break
+        fi
+      else
+        local connected=$(busctl --json short --system get-property \
+          net.connman.iwd "$object" \
+          net.connman.iwd.Network Connected 2>/dev/null | fj -r '.data')
+
+        if [ "$connected" = true ]; then
+          printf "> "
+        else
+          printf "  "
+        fi
+
+        printf "%s\n" "$name"
+      fi
+    done
+  }
 
 if ! selected=$(list_network | "$@"); then
   exit 1
 fi
 
-selected=${selected%%	*}
+selected=${selected#??}
 
-number=$(wpa_cli list_network | tail -n +3 | grep "	$selected	" | cut -f 1)
-wpa_cli -- select_network "$number"
+object_path=$(list_network "$selected")
+busctl --system call net.connman.iwd "$object_path" net.connman.iwd.Network Connect
