wifi-connect* now show helpful error message
wifi-connect-core now exit with predictable error code.
wifi-connect will print error message and the wifi-connect-gui
will send a desktop notification.

diff --git a/.local/bin/wifi-connect b/.local/bin/wifi-connect
--- a/.local/bin/wifi-connect
+++ b/.local/bin/wifi-connect
@@ -1,3 +1,14 @@
 #!/usr/bin/dash
 
-exec wifi-connect-core fzf
+wifi-connect-core fzf
+
+case "$?" in
+  64)
+    printf "%s\n" "No wireless interface"
+    exit 64
+    ;;
+  65)
+    printf "%s\n" "Unable to create config file"
+    exit 65
+    ;;
+esac
